Repository nephila/python-taiga, pull requests merged in 2019-05, with the labels that each got.

#66 Epic listing and instance support added
  taiga/client.py
  taiga/models/__init__.py
  taiga/models/models.py
  tests/resources/epic_details_success.json
  tests/resources/epics_list_success.json
  tests/test_epics.py
  tests/test_projects.py
Labels: status: review, type: feature

#84 Improve exception string representation
  taiga/exceptions.py
Labels: type: feature

#85 Improve epics support
  taiga/client.py
  taiga/models/models.py
  tests/resources/search_success.json
  tests/test_search.py
Labels: type: feature

#86 Remove demo.py
  .gitignore
  demo.py
Labels: type: bug

#87 Add support for python 3.7
  .travis.yml
  setup.py
  tox.ini
Labels: type: question
